# Dependencies
highlighter:      pygments



# Setup
title:            hlspace.org
tagline:          'Homelab space'
description:      'Homelab space'
url:              https://luizborgess.github.io
baseurl:          /

author:
  name:           'Luiz'

paginate:         5

# Custom vars
version:          2.1.0


# Gems
plugins:
  - jekyll-paginate

github:
  repo:           https://github.com/luizborgess/luizborgess.github.io
